version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: org.springframework.data:spring-data-mongodb
    versions:
    - 3.1.2
    - 3.1.3
  - dependency-name: org.springframework:spring-websocket
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework:spring-webmvc
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework:spring-web
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework:spring-test
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework:spring-context
    versions:
    - 5.3.2
    - 5.3.3
  - dependency-name: org.springframework.boot:spring-boot-starter-web
    versions:
    - 2.4.1
    - 2.4.2
  - dependency-name: org.springframework.security:spring-security-config
    versions:
    - 5.4.2
  - dependency-name: org.springframework.security:spring-security-taglibs
    versions:
    - 5.4.2
  - dependency-name: org.springframework.security:spring-security-web
    versions:
    - 5.4.2
